spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all


  datasource:
    url: jdbc:postgresql://localhost:5432/instant_payment
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082